apiVersion: v1
kind: Secret
metadata:
  name: coworking-secrets
  labels:
    app: coworking
    app.kubernetes.io/name: coworking
type: Opaque
data:
  # Base64-encoded PostgreSQL password from Helm installation
  DB_PASSWORD: "cTNla2FZUXI2Mw=="
